let TokenChatServiceBaseURLPath = "https://token-chat-service-development.herokuapp.com"
let TokenRatingsServiceBaseURLPath = "https://token-rep-service-development.herokuapp.com"
let TokenIdServiceBaseURLPath = "https://token-id-service-development.herokuapp.com"
let TokenEthereumServiceBaseURLPath = "https://token-eth-service-development.herokuapp.com"
let TokenDirectoryServiceBaseURLPath = "https://token-dir-service-development.herokuapp.com"
